@Library('idm-ci')
import idmci.*

env.IPA_EMAIL = 'spoore@redhat.com'
env.ANSIBLE_GATHER_TIMEOUT = '60'
env.VERSION = 'RHEL8.3'
env.TYPE = 'tier1'
env.NIGHTLY = 'true'
env.IDMCI_SLAVE = 'idm-ci-slave'
env.ABRT_EMAIL= 'spoore@redhat.com'

// Gating env vars
env.CI_NAME = 'IdM IPA CI'
env.CI_TEAM = 'IdM Eagle Team'
env.CI_DOCS = 'https://gitlab.cee.redhat.com/identity-management/idm-ci/blob/master/doc/user-doc.md'
env.CI_IRC = '#ipa'
env.CI_EMAIL = 'spoore@redhat.com'
env.ARTIFACT_NAMESPACE = 'idm-ci.brew-build'

def IPATESTS_METADATA_PATH = 'https://gitlab.cee.redhat.com/identity-management/ipa-tests/raw/RHEL8.3'

properties([
    parameters([    
    string(name: 'CI_MESSAGE', defaultValue: '', description: 'CI_MESSAGE'),
    string(name: 'MESSAGE_HEADERS', defaultValue: '', description: 'MESSAGE_HEADERS'),
    booleanParam(name: 'SKIP_UMB_MSG', defaultValue: false, description: 'True will cause no UMB messages.'),
    booleanParam(name: 'NOTIFY_PACKAGER', defaultValue: false, description: 'Notify packager about this jenkins build.'),
    booleanParam(name: 'DEBUG', defaultValue: true, description: 'Will printout debug information.'),
    string(name: 'RECIPIENTS', defaultValue: '', description: 'Email recipients'),
    booleanParam(name: 'BEAKER', defaultValue: false, description: 'True will cause Beaker provisioning.'),
    booleanParam(name: 'PERMISSIVE', defaultValue: false, description: 'True will cause to set selinux to permissive mode and no UMB messages will be published'),
    ]),
])

env.BEAKER = "${params.BEAKER}"

node {
  def g = new idmci.gating.gating()
  def failed = false
  // We init an in-progress message to be published as soon as this pipeline is triggered
  g.sendMessage('running')
  try {
        stage("tier-1") {
          parallel(
            "bash::web_app_authenitcation": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/web_app_authentication.yaml",
                    test: 'web_app_authentication',
                    email: 'spoore@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            )
        }
   } catch (e) {
       failed = true
   } finally {
       if (failed) {
         g.sendMessage('error')
         sh script: "exit 1", label: "Pipeline run failed"
       } else {
       g.sendMessage('complete')
      }
   }
}
