@Library('idm-ci')
import idmci.*

env.IPA_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ANSIBLE_GATHER_TIMEOUT = '60'
env.NIGHTLY = 'true'
env.IDMCI_SLAVE = 'idm-ci-slave'
env.ABRT_EMAIL= 'ipa-qe@redhat.com'

// syntax: cron(<minute> <hour> <day of month> <month> <day of week>) timezone: UTC
// details of jenkins cron sytax: https://jenkins.io/doc/book/pipeline/syntax/#cron-syntax
properties([
    pipelineTriggers([cron('30 23 * * 5')]),
])

node {
    try {
        new ComposeID().exec(env.IDMCI_SLAVE)
    } catch (Exception e) {
        sh script: "echo 'Display COMPOSE_ID unsuccessful'"
        currentBuild.result = 'SUCCESS'
    }
        stage("WebUI") {
          parallel(
            "webui::automember": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/automember.yaml',
                    test: 'webui-automember',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::automount": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/automount.yaml',
                    test: 'webui-automount',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::caless": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/caless.yaml',
                    test: 'webui-caless',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::cert": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/cert.yaml',
                    test: 'webui-cert',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::config": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/config.yaml',
                    test: 'webui-config',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::delegation": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/delegation.yaml',
                    test: 'webui-delegation',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::dns": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/dns.yaml',
                    test: 'webui-dns',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::group": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/group.yaml',
                    test: 'webui-group',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::hbac": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/hbac.yaml',
                    test: 'webui-hbac',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::hostgroup": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/hostgroup.yaml',
                    test: 'webui-hostgroup',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::host": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/host.yaml',
                    test: 'webui-host',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::idviews": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/idviews.yaml',
                    test: 'webui-idviews',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::krbtpolicy": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/krbtpolicy.yaml',
                    test: 'webui-krbtpolicy',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::loginscreen": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/loginscreen.yaml',
                    test: 'webui-loginscreen',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::misc_cases": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/misc_cases.yaml',
                    test: 'webui-misc_cases',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::navigation": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/navigation.yaml',
                    test: 'webui-navigation',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::netgroup": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/netgroup.yaml',
                    test: 'webui-netgroup',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::pwpolicy": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/pwpolicy.yaml',
                    test: 'webui-pwpolicy',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::range": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/range.yaml',
                    test: 'webui-range',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::rbac": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/rbac.yaml',
                    test: 'webui-rbac',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::realmdomains": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/realmdomains.yaml',
                    test: 'webui-realmdomains',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::selfservice": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/selfservice.yaml',
                    test: 'webui-selfservice',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::selinuxusermap": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/selinuxusermap.yaml',
                    test: 'webui-selinuxusermap',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::service": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/service.yaml',
                    test: 'webui-service',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::sudo": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/sudo.yaml',
                    test: 'webui-sudo',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::translation": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/translation.yaml',
                    test: 'webui-translation',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::trust": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/trust.yaml',
                    test: 'upstream-trust',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::user": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/user.yaml',
                    test: 'webui-user',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::vault": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/vault.yaml',
                    test: 'webui-vault',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "webui::trust": {
                new TeRun([
                    metadata: 'metadata/upstream/webui/trust.yaml',
                    test: 'webui-trust',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            }
            )
        }
}

