@Library('idm-ci')
import idmci.*

env.IDMCI_GITREPO = 'https://gitlab.cee.redhat.com/identity-management/idm-ci.git'
env.IDMCI_BRANCH = 'production'
env.IPA_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ANSIBLE_GATHER_TIMEOUT = '60'
env.VERSION = 'RHEL8.2'
env.TYPE = 'client-stream.tier1'
env.NIGHTLY = 'true'

// Gating env vars
env.CI_NAME = 'IdM IPA CI'
env.CI_TEAM = 'IdM Eagle Team'
env.CI_DOCS = 'https://gitlab.cee.redhat.com/identity-management/idm-ci/blob/master/doc/user-doc.md'
env.CI_IRC = '#ipa'
env.CI_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ARTIFACT_NAMESPACE = 'idm-ci.redhat-module'

properties([
    parameters([
    string(name: 'CI_MESSAGE', defaultValue: '', description: 'CI_MESSAGE'),
    string(name: 'MESSAGE_HEADERS', defaultValue: '', description: 'MESSAGE_HEADERS'),
    booleanParam(name: 'SKIP_UMB_MSG', defaultValue: false, description: 'True will cause no UMB messages.'),
    booleanParam(name: 'NOTIFY_PACKAGER', defaultValue: false, description: 'Notify packager about this jenkins build.'),
    booleanParam(name: 'DEBUG', defaultValue: true, description: 'Will printout debug information.'),
    string(name: 'RECIPIENTS', defaultValue: '', description: 'Email recipients'),
    ]),
])

node {
  def g = new idmci.gating.gating()
  def failed = false
  // We init an in-progress message to be published as soon as this pipeline is triggered
  g.sendMessage('running')
  try {
        stage("tier-1") {
          parallel(
          "pytest::functional_services": {
                new TeRun([
                    metadata: 'metadata/pytests/functional_services.yaml',
                    test: 'pytests-functional_services',
                    email: 'ipa-and-samba-team-automation@redhat.com'
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            }
            )
        }
   } catch (e) {
       failed = true
   } finally {
       if (failed) {
         g.sendMessage('error')
         sh script: "exit 1", label: "Pipeline run failed"
       } else {
       g.sendMessage('complete')
       }
   }
}

