image:
  name: docker-registry.upshift.redhat.com/idm/idm-test-slave:latest
  entrypoint: [""]

.mr_template: &mr_definition
  tags:
  - shared
  only:
  - merge_requests
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week

before_script:
- git clone https://gitlab.cee.redhat.com/identity-management/idm-ci.git

ipa-mr-pipeline:
  <<: *mr_definition
  script:
  - bash idm-ci/scripts/mr_workflow.sh

