image:
  name: docker-registry.upshift.redhat.com/idm/idm-test-slave:latest
  entrypoint: [""]

.mr_template:
  tags:
  - shared
  only:
    refs:
    - merge_requests
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
  script:
  - idm-ci/scripts/fork_updater.py --metadata-file $METADATA_FILE_PATH
  - idm-ci/scripts/te $METADATA_FILE_PATH

.mr_backport_template: &mr_backport_definition
  tags:
  - shared
  only:
  - /^RHEL*/

before_script:
- git clone -b production --depth=1 https://gitlab.cee.redhat.com/identity-management/idm-ci.git
- pip3 install ./idm-ci

backport-mr:
  <<: *mr_backport_definition
  script:
  - python3 idm-ci/scripts/backport_mr.py

include:
  - local: '.pytests-jobs.yml'
  - local: '.upstream-jobs.yml'
