@Library('idm-ci')
import idmci.*

env.IPA_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ANSIBLE_GATHER_TIMEOUT = '60'
env.NIGHTLY = 'true'
env.IDMCI_SLAVE = 'idm-ci-slave'
env.ABRT_EMAIL= 'ipa-qe@redhat.com'

def IPATESTS_METADATA_PATH = 'https://gitlab.cee.redhat.com/identity-management/ipa-tests/raw/RHEL8.4'

// syntax: cron(<minute> <hour> <day of month> <month> <day of week>) timezone: UTC
// details of jenkins cron sytax: https://jenkins.io/doc/book/pipeline/syntax/#cron-syntax
properties([
    pipelineTriggers([cron('0 19 * * 5')]),
])

node {
    try {
        new ComposeID().exec(env.IDMCI_SLAVE)
    } catch (Exception e) {
        sh script: "echo 'Display COMPOSE_ID unsuccessful'"
        currentBuild.result = 'SUCCESS'
    }
        stage("tier-1") {
          parallel(
            "bash::ipa-automember": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-automember.yaml",
                    test: 'ipa-automember',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-automount": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-automount.yaml",
                    test: 'ipa-automount',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-config": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-config.yaml",
                    test: 'ipa-config',
                    email: 'sorlov@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::cert": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-cert.yaml",
                    test: 'ipa-cert',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-ctl": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-ctl.yaml",
                    test: 'ipa-ctl',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-default": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-default.yaml",
                    test: 'ipa-default',
                    email: 'amore@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-delegation-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-delegation-cli.yaml",
                    test: 'ipa-delegation-cli',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::dns": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-dns.yaml",
                    test: 'ipa-dns',
                    email: 'sorlov@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::getcert": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-getcert.yaml",
                    test: 'ipa-getcert',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-get-rm-keytab": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-get-rm-keytab.yaml",
                    test: 'ipa-get-rm-keytab',
                    email: 'ksiddiqu@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-group-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-group-cli.yaml",
                    test: 'ipa-group-cli',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-hbac-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-hbac-cli.yaml",
                    test: 'ipa-hbac-cli',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-hbac-func": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-hbac-func.yaml",
                    test: 'ipa-hbac-func',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-hbacsvc-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-hbacsvc-cli.yaml",
                    test: 'ipa-hbacsvc-cli',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-host-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-host-cli.yaml",
                    test: 'ipa-host-cli',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-hostgroup-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-hostgroup-cli.yaml",
                    test: 'ipa-hostgroup-cli',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-i18n": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-i18n.yaml",
                    test: 'ipa-i18n',
                    email: 'amore@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::krbtpolicy": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-krbtpolicy.yaml",
                    test: 'ipa-krbtpolicy',
                    email: 'sorlov@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-migration": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-migration.yaml",
                    test: 'ipa-migration',
                    email: 'ndehadra@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-netgroup-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-netgroup-cli.yaml",
                    test: 'ipa-netgroup-cli',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::password": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-password.yaml",
                    test: 'ipa-password',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-selfservice": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-selfservice.yaml",
                    test: 'ipa-selfservice',
                    email: 'mvarun@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-selinuxusermap-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-selinuxusermap-cli.yaml",
                    test: 'ipa-selinuxusermap-cli',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-services": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-services.yaml",
                    test: 'ipa-services',
                    email: 'amore@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ssh-functional": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-ssh-functional.yaml",
                    test: 'ipa-ssh-functional',
                    email: 'mvarun@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::sudo": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-sudo.yaml",
                    test: 'ipa-sudo',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::trust-functional-ssh": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-trust-func-ssh.yaml",
                    test: 'ipa-trust-functional-ssh',
                    email: 'ksiddiqu@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::trust-functional-user": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-trust-func-user.yaml",
                    test: 'ipa-trust-functional-user',
                    email: 'amore@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-upgrade_normal": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-upgrade_normal.yaml",
                    test: 'ipa-upgrade_normal',
                    email: 'ndehadra@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-upgrade_bztests": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-upgrade_bztests.yaml",
                    test: 'ipa-upgrade_bztests',
                    email: 'ndehadra@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-upgrade_parallel": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-upgrade_parallel.yaml",
                    test: 'ipa-upgrade_parallel',
                    email: 'ndehadra@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-upgrade_reverse": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-upgrade_reverse.yaml",
                    test: 'ipa-upgrade_reverse',
                    email: 'ndehadra@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ipa-upgrade_dirsrvoff": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-upgrade_dirsrvoff.yaml",
                    test: 'ipa-upgrade_dirsrvoff',
                    email: 'ndehadra@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::user-cli-adduser": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-user-cli-adduser.yaml",
                    test: 'ipa-user-cli-adduser',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::user-cli-moduser": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-user-cli-moduser.yaml",
                    test: 'ipa-user-cli-moduser',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::client_install": {
                new TeRun([
                    metadata: 'metadata/pytests/client_install.yaml',
                    test: 'client_install',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::dns_services": {
                new TeRun([
                    metadata: 'metadata/pytests/dns_services.yaml',
                    test: 'dns_services',
                    email: 'amore@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::external-ca": {
                new TeRun([
                    metadata: 'metadata/pytests/external-ca.yaml',
                    test: 'ipa-external-ca',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::func-svcs": {
                new TeRun([
                    metadata: 'metadata/pytests/functional_services.yaml',
                    test: 'ipa-functional_services',
                    email: 'ksiddiqu@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::ipa-advise": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-advise.yaml',
                    test: 'ipa-advise',
                    email: 'ksiddiqu@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::ipa-cert": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-cert.yaml',
                    test: 'ipa-cert',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::ipa-certprofile": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-certprofile.yaml',
                    test: 'ipa-certprofile',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::ipa-getcert": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-getcert.yaml',
                    test: 'ipa-getcert',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::ipa-hbac": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-hbac.yaml',
                    test: 'ipa-hbac',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::ipa-hosts": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-host.yaml',
                    test: 'pytests-ipa-host',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::ipa-rbac": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-rbac.yaml',
                    test: 'ipa-rbac',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::replica-promotion": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-replica-promotion.yaml',
                    test: 'ipa-replica-promotion',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::otp": {
                new TeRun([
                    metadata: 'metadata/pytests/otp.yaml',
                    test: 'otp',
                    email: 'amore@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::subca": {
                new TeRun([
                    metadata: 'metadata/pytests/subca.yaml',
                    test: 'ipa-subca',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::ipa-upgrade-healthcheck": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa_upgrade_healthcheck.yaml',
                    test: 'ipa-upgrade-healthcheck',
                    email: 'ssidhaye@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::healthcheck": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/healthcheck.yaml',
                    test: 'upstream-healthcheck',
                    email: 'sumenon@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::cert": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/cert.yaml',
                    test: 'upstream-cert',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::adtrust_install": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/adtrust_install.yaml',
                    test: 'upstream-adtrust_install',
                    email: 'sorlov@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::advise": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/advise.yaml',
                    test: 'upstream-advise',
                    email: 'ksiddiqu@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::authselect": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/authselect.yaml',
                    test: 'upstream-authselect',
                    email: 'frenaud@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::caless-TestServerInstall": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestServerInstall.yaml',
                    test: 'upstream-caless-TestServerInstall',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::caless-TestReplicaInstall": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestReplicaInstall.yaml',
                    test: 'upstream-caless-TestReplicaInstall',
                    email: 'myusuf@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::commands": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/commands.yaml',
                    test: 'upstream-commands',
                    email: 'ksiddiqu@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::krbtpolicy": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/krbtpolicy.yaml',
                    test: 'upstream-krbtpolicy',
                    email: 'sorlov@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::nfs": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/nfs.yaml',
                    test: 'upstream-nfs',
                    email: 'mvarun@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::pki_config_override": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/pki_config_override.yaml',
                    test: 'upstream-pki_config_override',
                    email: 'ksiddiqu@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::otp": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/otp.yaml',
                    test: 'upstream-otp',
                    email: 'amore@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::membermanager": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/membermanager.yaml',
                    test: 'upstream-membermanager',
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::smb": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/smb.yaml',
                    test: 'upstream-smb',
                    email: 'sorlov@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::xmlrpc": {
                new TeRun([
                    metadata: 'metadata/upstream/xmlrpc/xmlrpc-tests.yaml',
                    test: 'upstream-xmlrpc',
                    email: 'sorlov@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::dns": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/dns.yaml',
                    test: 'upstream-dns',
                    email: 'amore@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::epn": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/epn.yaml',
                    test: 'upstream-epn',
                    email: 'mpolovka@redhat.com'
                ]).exec(env.IDMCI_SLAVE)
            }
            )
        }
}

