@Library('idm-ci')
import idmci.*

env.IDMCI_GITREPO = 'https://gitlab.cee.redhat.com/identity-management/idm-ci.git'
env.IPA_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ANSIBLE_GATHER_TIMEOUT = '60'

node {
        stage("tier-2") {
          parallel(
            "pytests::ipa-hosts": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-hosts.yaml',
                    test: 'pytests-ipa-hosts'
                ]).exec('ipa-slave')
            },
            "ipatests::ipa-getcert": {
                new TeRun([
                    metadata: 'metadata/ipatests/ipa-getcert.yaml',
                    test: 'ipatests-ipa-getcert'
                ]).exec('ipa-slave')
            },
            "pytests::upstream-crlgen-manage": {
                new TeRun([
                    metadata: 'metadata/pytests/upstream-crlgen-manage.yaml',
                    test: 'pytests-upstream-crlgen-manage'
                ]).exec('ipa-slave')
            },
            "ipatests::ipa-client-automount": {
                new TeRun([
                    metadata: 'metadata/ipatests/ipa-client-automount.yaml',
                    test: 'ipatests-ipa-client-automount'
                ]).exec('ipa-slave')
            },
            "ipatests::kdcproxy": {
                new TeRun([
                    metadata: 'metadata/ipatests/kdcproxy.yaml',
                    test: 'ipatests-kdcproxy'
                ]).exec('ipa-slave')
            },
            "ipatests::ipa-get-rm-keytab": {
                new TeRun([
                    metadata: 'metadata/ipatests/ipa-get-rm-keytab.yaml',
                    test: 'ipatests-ipa-get-rm-keytab'
                ]).exec('ipa-slave')
            }
            )
        }
}
