@Library('idm-ci')
import idmci.*

env.IDMCI_GITREPO = 'https://gitlab.cee.redhat.com/identity-management/idm-ci.git'
env.IDMCI_BRANCH = 'production'
env.IPA_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ANSIBLE_GATHER_TIMEOUT = '60'
env.NIGHTLY = 'true'

def IPATESTS_METADATA_PATH = 'https://gitlab.cee.redhat.com/identity-management/ipa-tests/raw/RHEL8.2'

// syntax: cron(<minute> <hour> <day of month> <month> <day of week>) timezone: UTC
// details of jenkins cron sytax: https://jenkins.io/doc/book/pipeline/syntax/#cron-syntax
properties([pipelineTriggers([cron('30 20 * * 2,5')])])

node {
        stage("tier-2") {
          parallel(
            "pytest::external_trust": {
                new TeRun([
                    metadata: 'metadata/pytests/external_trust.yaml',
                    test: 'external_trust'
                ]).exec('ipa-slave')
            },
            "pytest::ipa-backup-restore": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-backup-restore.yaml',
                    test: 'ipa-backup-restore'
                ]).exec('ipa-slave')
            },
            "pytest::ipa-idoverride": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-idoverride.yaml',
                    test: 'ipa-idoverride'
                ]).exec('ipa-slave')
            },
            "pytest::ipa-nis-manage": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-nis-manage.yaml',
                    test: 'ipa-nis-manage'
                ]).exec('ipa-slave')
            },
            "pytest::ipa-services": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-services.yaml',
                    test: 'ipa-services'
                ]).exec('ipa-slave')
            },
            "pytest::ipa-sudo": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-sudo.yaml',
                    test: 'ipa-sudo'
                ]).exec('ipa-slave')
            },
            "pytest::ipa-user": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-user.yaml',
                    test: 'ipa-user'
                ]).exec('ipa-slave')
            },
            "pytest::kdcproxy": {
                new TeRun([
                    metadata: 'metadata/pytests/kdcproxy.yaml',
                    test: 'kdcproxy'
                ]).exec('ipa-slave')
            },
            "pytest::replica-install": {
                new TeRun([
                    metadata: 'metadata/pytests/replica-install.yaml',
                    test: 'replica-install'
                ]).exec('ipa-slave')
            },
            "pytest::server-role": {
                new TeRun([
                    metadata: 'metadata/pytests/server-role.yaml',
                    test: 'server-role'
                ]).exec('ipa-slave')
            },
            "pytest::sudo-ipa-schema": {
                new TeRun([
                    metadata: 'metadata/pytests/sudo-ipa-schema.yaml',
                    test: 'sudo-ipa-schema'
                ]).exec('ipa-slave')
            },
            "pytest::trust_one_way": {
                new TeRun([
                    metadata: 'metadata/pytests/trust_one_way.yaml',
                    test: 'trust_one_way'
                ]).exec('ipa-slave')
            },
            "pytest::upn": {
                new TeRun([
                    metadata: 'metadata/pytests/upn.yaml',
                    test: 'upn'
                ]).exec('ipa-slave')
            },
            "pytest::vault": {
                new TeRun([
                    metadata: 'metadata/pytests/vault.yaml',
                    test: 'vault'
                ]).exec('ipa-slave')
            },
            "bash::ds-migration": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ds-migration.yaml",
                    test: 'ds-migration'
                ]).exec('ipa-slave')
            },
            "bash::ds-migration-func": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ds-migration-func.yaml",
                    test: 'ds-migration-func'
                ]).exec('ipa-slave')
            },
            "bash::ipa-client-cert": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-client-cert.yaml",
                    test: 'ipa-client-cert'
                ]).exec('ipa-slave')
            },
            "bash::install-client-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/install-client-cli.yaml",
                    test: 'install-client-cli'
                ]).exec('ipa-slave')
            },
            "bash::ipa-adtrust": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-adtrust.yaml",
                    test: 'ipa-adtrust'
                ]).exec('ipa-slave')
            },
            "bash::ipa-client-automount": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-client-automount.yaml",
                    test: 'ipa-client-automount'
                ]).exec('ipa-slave')
            },
            "bash::ipa-idrange-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-idrange-cli.yaml",
                    test: 'ipa-idrange-cli'
                ]).exec('ipa-slave')
            },
            "bash::ipa-join": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-join.yaml",
                    test: 'ipa-join'
                ]).exec('ipa-slave')
            },
            "bash::ipa-krblockout": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-krblockout.yaml",
                    test: 'ipa-krblockout'
                ]).exec('ipa-slave')
            },
            "bash::ipa-nis-integration": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-nis-integration.yaml",
                    test: 'ipa-nis-integration'
                ]).exec('ipa-slave')
            },
            "bash::ipa-realmdomains-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-realmdomains-cli.yaml",
                    test: 'ipa-realmdomains-cli'
                ]).exec('ipa-slave')
            },
            "bash::ipa-selinuxusermap-func": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-selinuxusermap-func.yaml",
                    test: 'ipa-selinuxusermap-func'
                ]).exec('ipa-slave')
            },
            "bash::ipa-trust-cli": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-trust-cli.yaml",
                    test: 'ipa-trust-cli'
                ]).exec('ipa-slave')
            },
            "bash::ipa-trust-func-hbac": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-trust-func-hbac.yaml",
                    test: 'ipa-trust-func-hbac'
                ]).exec('ipa-slave')
            },
            "bash::ipa-trust-func-httpkrb": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-trust-func-httpkrb.yaml",
                    test: 'ipa-trust-func-httpkrb'
                ]).exec('ipa-slave')
            },
            "bash::ipa-trust-func-selinux-usermap": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-trust-func-selinux-usermap.yaml",
                    test: 'ipa-trust-func-selinux-usermap'
                ]).exec('ipa-slave')
            },
            "bash::ipa-trust-func-automount": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-trust-func-automount.yaml",
                    test: 'ipa-trust-func-automount'
                ]).exec('ipa-slave')
            },
            "bash::ipa-trust-func-sudo": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-trust-func-sudo.yaml",
                    test: 'ipa-trust-func-sudo'
                ]).exec('ipa-slave')
            },
            "upstream::automember": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/automember.yaml',
                    test: 'upstream-automember'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupAndRestore": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupAndRestore.yaml',
                    test: 'upstream-backup_and_restore-TestBackupAndRestore'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupAndRestoreDMPassword": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupAndRestoreDMPassword.yaml',
                    test: 'upstream-backup_and_restore-TestBackupAndRestoreDMPassword'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupAndRestoreWithDNS": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupAndRestoreWithDNS.yaml',
                    test: 'upstream-backup_and_restore-TestBackupAndRestoreWithDNS'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupAndRestoreWithDNSSEC": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupAndRestoreWithDNSSEC.yaml',
                    test: 'upstream-backup_and_restore-TestBackupAndRestoreWithDNSSEC'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupAndRestoreWithKRA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupAndRestoreWithKRA.yaml',
                    test: 'upstream-backup_and_restore-TestBackupAndRestoreWithKRA'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupAndRestoreWithReplica": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupAndRestoreWithReplica.yaml',
                    test: 'upstream-backup_and_restore-TestBackupAndRestoreWithReplica'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupReinstallRestoreWithDNS": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupReinstallRestoreWithDNS.yaml',
                    test: 'upstream-backup_and_restore-TestBackupReinstallRestoreWithDNS'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupReinstallRestoreWithDNSSEC": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupReinstallRestoreWithDNSSEC.yaml',
                    test: 'upstream-backup_and_restore-TestBackupReinstallRestoreWithDNSSEC'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestBackupReinstallRestoreWithKRA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestBackupReinstallRestoreWithKRA.yaml',
                    test: 'upstream-backup_and_restore-TestBackupReinstallRestoreWithKRA'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestReplicainstallAfterRestore": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestReplicainstallAfterRestore.yaml',
                    test: 'upstream-backup_and_restore-TestReplicainstallAfterRestore'
                ]).exec('ipa-slave')
            },
            "upstream::backup_and_restore-TestUserRootFilesownershipPermiss": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/backup_and_restore-TestUserRootFilesownershipPermiss.yaml',
                    test: 'upstream-backup_and_restore-TestUserRootFilesownershipPermiss'
                ]).exec('ipa-slave')
            },
            "upstream::caless-TestCertinstall": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestCertinstall.yaml',
                    test: 'upstream-caless-TestCertinstall'
                ]).exec('ipa-slave')
            },
            "upstream::caless-TestClientinstall": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestClientinstall.yaml',
                    test: 'upstream-caless-TestClientinstall'
                ]).exec('ipa-slave')
            },
            "upstream::caless-TestIPACommands": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestIPACommands.yaml',
                    test: 'upstream-caless-TestIPACommands'
                ]).exec('ipa-slave')
            },
            "upstream::caless-TestPKINIT": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestPKINIT.yaml',
                    test: 'upstream-caless-TestPKINIT'
                ]).exec('ipa-slave')
            },
            "upstream::caless-TestReplicaCALessToCAFull": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestReplicaCALessToCAFull.yaml',
                    test: 'upstream-caless-TestReplicaCALessToCAFull'
                ]).exec('ipa-slave')
            },
            "upstream::caless-TestServerCALessToExternalCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestServerCALessToExternalCA.yaml',
                    test: 'upstream-caless-TestServerCALessToExternalCA'
                ]).exec('ipa-slave')
            },
            "upstream::caless-TestServerReplicaCALessToCAFull": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/caless-TestServerReplicaCALessToCAFull.yaml',
                    test: 'upstream-caless-TestServerReplicaCALessToCAFull'
                ]).exec('ipa-slave')
            },
            "upstream::crlgen_manage": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/crlgen_manage.yaml',
                    test: 'upstream-crlgen_manage'
                ]).exec('ipa-slave')
            },
            "upstream::customized_ds_config_install": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/customized_ds_config_install.yaml',
                    test: 'upstream-customized_ds_config_install'
                ]).exec('ipa-slave')
            },
            "upstream::dns_locations": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/dns_locations.yaml',
                    test: 'upstream-dns_locations'
                ]).exec('ipa-slave')
            },
            "upstream::external_ca-TestExternalCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/external_ca-TestExternalCA.yaml',
                    test: 'upstream-external_ca-TestExternalCA'
                ]).exec('ipa-slave')
            },
            "upstream::external_ca-TestSelfExternalSelf": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/external_ca-TestSelfExternalSelf.yaml',
                    test: 'upstream-external_ca-TestSelfExternalSelf'
                ]).exec('ipa-slave')
            },
            "upstream::external_ca-TestExternalCAinvalidCert": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/external_ca-TestExternalCAinvalidCert.yaml',
                    test: 'upstream-external_ca-TestExternalCAinvalidCert'
                ]).exec('ipa-slave')
            },
            "upstream::external_ca-TestExternalCAdirsrvStop": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/external_ca-TestExternalCAdirsrvStop.yaml',
                    test: 'upstream-external_ca-TestExternalCAdirsrvStop'
                ]).exec('ipa-slave')
            },
            "upstream::external_ca-TestMultipleExternalCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/external_ca-TestMultipleExternalCA.yaml',
                    test: 'upstream-external_ca-TestMultipleExternalCA'
                ]).exec('ipa-slave')
            },
            "upstream::external_ca-TestExternalCAProfileScenarios": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/external_ca-TestExternalCAProfileScenarios.yaml',
                    test: 'upstream-external_ca-TestExternalCAProfileScenarios'
                ]).exec('ipa-slave')
            },
            "upstream::forced_client_reenrollment": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/forced_client_reenrollment.yaml',
                    test: 'upstream-forced_client_reenrollment'
                ]).exec('ipa-slave')
            },
            "upstream::http_kdc_proxy": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/http_kdc_proxy.yaml',
                    test: 'upstream-http_kdc_proxy'
                ]).exec('ipa-slave')
            },
            "upstream::idviews": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/idviews.yaml',
                    test: 'upstream-idviews'
                ]).exec('ipa-slave')
            },
            "upstream::kerberos_flags": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/kerberos_flags.yaml',
                    test: 'upstream-kerberos_flags'
                ]).exec('ipa-slave')
            },
            "upstream::legacy_clients": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/legacy_clients.yaml',
                    test: 'upstream-legacy_clients'
                ]).exec('ipa-slave')
            },
            "upstream::netgroup": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/netgroup.yaml',
                    test: 'upstream-netgroup'
                ]).exec('ipa-slave')
            },
            "upstream::pkinit_manage": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/pkinit_manage.yaml',
                    test: 'upstream-pkinit_manage'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestHiddenReplicaPromotion": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestHiddenReplicaPromotion.yaml',
                    test: 'upstream-replica_promotion-TestHiddenReplicaPromotion'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestProhibitReplicaUninstallation": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestProhibitReplicaUninstallation.yaml',
                    test: 'upstream-replica_promotion-TestProhibitReplicaUninstallation'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestRenewalMaster": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestRenewalMaster.yaml',
                    test: 'upstream-replica_promotion-TestRenewalMaster'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestReplicainForwardZone": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestReplicainForwardZone.yaml',
                    test: 'upstream-replica_promotion-TestReplicainForwardZone'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestReplicainstallCustodia": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestReplicainstallCustodia.yaml',
                    test: 'upstream-replica_promotion-TestReplicainstallCustodia'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestReplicainstallWithExistingEntry": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestReplicainstallWithExistingEntry.yaml',
                    test: 'upstream-replica_promotion-TestReplicainstallWithExistingEntry'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestReplicaPromotionLevel1": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestReplicaPromotionLevel1.yaml',
                    test: 'upstream-replica_promotion-TestReplicaPromotionLevel1'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestSubCAkeyReplication": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestSubCAkeyReplication.yaml',
                    test: 'upstream-replica_promotion-TestSubCAkeyReplication'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestUnprivilegedUserPermissions": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestUnprivilegedUserPermissions.yaml',
                    test: 'upstream-replica_promotion-TestUnprivilegedUserPermissions'
                ]).exec('ipa-slave')
            },
            "upstream::replica_promotion-TestWrongClientDomain": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replica_promotion-TestWrongClientDomain.yaml',
                    test: 'upstream-replica_promotion-TestWrongClientDomain'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestStarTopologyWithoutCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestStarTopologyWithoutCA.yaml',
                    test: 'upstream-replication_layouts-TestStarTopologyWithoutCA'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestCompleteTopologyWithCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestCompleteTopologyWithCA.yaml',
                    test: 'upstream-replication_layouts-TestCompleteTopologyWithCA'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestCompleteTopologyWithCAKRA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestCompleteTopologyWithCAKRA.yaml',
                    test: 'upstream-replication_layouts-TestCompleteTopologyWithCAKRA'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestCompleteTopologyWithoutCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestCompleteTopologyWithoutCA.yaml',
                    test: 'upstream-replication_layouts-TestCompleteTopologyWithoutCA'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestLineTopologyWithCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestLineTopologyWithCA.yaml',
                    test: 'upstream-replication_layouts-TestLineTopologyWithCA'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestLineTopologyWithCAKRA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestLineTopologyWithCAKRA.yaml',
                    test: 'upstream-replication_layouts-TestLineTopologyWithCAKRA'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestLineTopologyWithoutCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestLineTopologyWithoutCA.yaml',
                    test: 'upstream-replication_layouts-TestLineTopologyWithoutCA'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestStarTopologyWithCA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestStarTopologyWithCA.yaml',
                    test: 'upstream-replication_layouts-TestStarTopologyWithCA'
                ]).exec('ipa-slave')
            },
            "upstream::replication_layouts-TestStarTopologyWithCAKRA": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/replication_layouts-TestStarTopologyWithCAKRA.yaml',
                    test: 'upstream-replication_layouts-TestStarTopologyWithCAKRA'
                ]).exec('ipa-slave')
            },
            "upstream::server_del": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/server_del.yaml',
                    test: 'upstream-server_del'
                ]).exec('ipa-slave')
            },
            "upstream::service_permissions": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/service_permissions.yaml',
                    test: 'upstream-service_permissions'
                ]).exec('ipa-slave')
            },
            "upstream::sudo": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/sudo.yaml',
                    test: 'upstream-sudo'
                ]).exec('ipa-slave')
            },
            "upstream::topology-TestCASpecificRUVs": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/topology-TestCASpecificRUVs.yaml',
                    test: 'upstream-topology-TestCASpecificRUVs'
                ]).exec('ipa-slave')
            },
            "upstream::topology-TestTopologyOptions": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/topology-TestTopologyOptions.yaml',
                    test: 'upstream-topology-TestTopologyOptions'
                ]).exec('ipa-slave')
            },
            "upstream::trust": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/trust.yaml',
                    test: 'upstream-trust'
                ]).exec('ipa-slave')
            },
            "upstream::user_permissions": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/user_permissions.yaml',
                    test: 'upstream-user_permissions'
                ]).exec('ipa-slave')
            },
            "upstream::vault": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/vault.yaml',
                    test: 'upstream-vault'
                ]).exec('ipa-slave')
            },
            "upstream::winsyncmigrate": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/winsyncmigrate.yaml',
                    test: 'upstream-winsyncmigrate'
                ]).exec('ipa-slave')
            }
            )
        }
}
