@Library('idm-ci')
import idmci.*

env.IPA_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ANSIBLE_GATHER_TIMEOUT = '60'
env.VERSION = 'RHEL8.3'
env.TYPE = 'tier1'
env.NIGHTLY = 'true'
env.IDMCI_SLAVE = 'idm-ci-slave'
env.ABRT_EMAIL= 'ipa-qe@redhat.com'

// Gating env vars
env.CI_NAME = 'IdM IPA CI'
env.CI_TEAM = 'IdM Eagle Team'
env.CI_DOCS = 'https://gitlab.cee.redhat.com/identity-management/idm-ci/blob/master/doc/user-doc.md'
env.CI_IRC = '#ipa'
env.CI_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ARTIFACT_NAMESPACE = 'idm-ci.brew-build'

def IPATESTS_METADATA_PATH = 'https://gitlab.cee.redhat.com/identity-management/ipa-tests/raw/RHEL8.3'

properties([
    parameters([    
    string(name: 'CI_MESSAGE', defaultValue: '', description: 'CI_MESSAGE'),
    string(name: 'MESSAGE_HEADERS', defaultValue: '', description: 'MESSAGE_HEADERS'),
    booleanParam(name: 'SKIP_UMB_MSG', defaultValue: true, description: 'True will cause no UMB messages.'),
    booleanParam(name: 'NOTIFY_PACKAGER', defaultValue: false, description: 'Notify packager about this jenkins build.'),
    booleanParam(name: 'DEBUG', defaultValue: true, description: 'Will printout debug information.'),
    string(name: 'RECIPIENTS', defaultValue: '', description: 'Email recipients'),
    booleanParam(name: 'BEAKER', defaultValue: false, description: 'True will cause Beaker provisioning.'),
    booleanParam(name: 'PERMISSIVE', defaultValue: false, description: 'True will cause to set selinux to permissive mode and no UMB messages will be published'),
    ]),
])

env.BEAKER = "${params.BEAKER}"

node {
  def g = new idmci.gating.gating()
  def failed = false
  // We init an in-progress message to be published as soon as this pipeline is triggered
  g.sendMessageBrew('running')
  try {
        stage("tier-1") {
          parallel(
            "pytest::ipa-hosts": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-host.yaml',
                    test: 'pytests-ipa-host',
                    email: 'sumenon@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::subca": {
                new TeRun([
                    metadata: 'metadata/pytests/subca.yaml',
                    test: 'ipa-subca',
                    email: 'ssidhaye@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::external-ca": {
                new TeRun([
                    metadata: 'metadata/pytests/external-ca.yaml',
                    test: 'ipa-external-ca',
                    email: 'ssidhaye@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::otp": {
                new TeRun([
                    metadata: 'metadata/pytests/otp.yaml',
                    test: 'otp',
                    email: 'amore@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::vault": {
                new TeRun([
                    metadata: 'metadata/pytests/vault.yaml',
                    test: 'vault',
                    email: 'ssidhaye@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::replica-install": {
                new TeRun([
                    metadata: 'metadata/pytests/replica-install.yaml',
                    test: 'ipa-replica-install',
                    email: 'sumenon@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "pytest::replica-promotion": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-replica-promotion.yaml',
                    test: 'ipa-replica-promotion',
                    email: 'sumenon@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::krbtpolicy": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-krbtpolicy.yaml",
                    test: 'ipa-krbtpolicy',
                    email: 'sorlov@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "upstream::krbtpolicy": {
                new TeRun([
                    metadata: 'metadata/upstream/integration/krbtpolicy.yaml',
                    test: 'upstream-krbtpolicy',
                    email: 'sorlov@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::ssh-functional": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-ssh-functional.yaml",
                    test: 'ipa-ssh-functional',
                    email: 'mvarun@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::user-cli-adduser": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-user-cli-adduser.yaml",
                    test: 'ipa-user-cli-adduser',
                    email: 'sumenon@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            },
            "bash::user-cli-moduser": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-user-cli-moduser.yaml",
                    test: 'ipa-user-cli-moduser',
                    email: 'sumenon@redhat.com',
                    message: "${params.CI_MESSAGE}"
                ]).exec(env.IDMCI_SLAVE)
            }
            )
        }
   } catch (e) {
       failed = true
   } finally {
       if (failed) {
         g.sendMessageBrew('error')
         sh script: "exit 1", label: "Pipeline run failed"
       } else {
       g.sendMessageBrew('complete')
      }
   }
}
