@Library('idm-ci')
import idmci.*

env.IDMCI_GITREPO = 'https://gitlab.cee.redhat.com/identity-management/idm-ci.git'
env.IDMCI_BRANCH = 'production'
env.IPA_EMAIL = 'ipa-and-samba-team-automation@redhat.com'
env.ANSIBLE_GATHER_TIMEOUT = '60'

def IPATESTS_METADATA_PATH = 'https://gitlab.cee.redhat.com/identity-management/ipa-tests/raw/master'

properties([
    parameters([
    string(name: 'CI_MESSAGE', defaultValue: '', description: 'CI_MESSAGE'),
    string(name: 'MESSAGE_HEADERS', defaultValue: '', description: 'MESSAGE_HEADERS')
    ]),
    pipelineTriggers([
    [
        $class: 'CIBuildTrigger',
        noSquash: false,
        providerData: [
        $class: 'ActiveMQSubscriberProviderData',
        checks: [
            [
            expectedValue: 'tier0',
            field: 'type'
            ],
            [
            expectedValue: 'idm',
            field: 'artifact.name'
            ],
            [
            expectedValue: 'DL1',
            field: 'artifact.stream'
            ],
            [
            expectedValue: 'passed',
            field: 'status'
            ]
        ],
        name: 'Red Hat UMB',
        overrides: [
            topic: 'Consumer.rh-jenkins-ci-plugin.e1a8f4a3-3a25-4919-b2b9-080614de8fb6.VirtualTopic.eng.ci.redhat-module.test.complete'
        ],
        selector: '',
        timeout: null
        ]
    ]
    ])
])

node {
  sh "touch /tmp/tier1_status"
  try {
        stage("tier-1") {
          parallel(
            "pytest::ipa-hosts": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-host.yaml',
                    test: 'pytests-ipa-host',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "pytest::subca": {
                new TeRun([
                    metadata: 'metadata/pytests/subca.yaml',
                    test: 'ipa-subca',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "pytest::external-ca": {
                new TeRun([
                    metadata: 'metadata/pytests/external-ca.yaml',
                    test: 'ipa-external-ca',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "pytest::otp": {
                new TeRun([
                    metadata: 'metadata/pytests/otp.yaml',
                    test: 'otp',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "pytest::vault": {
                new TeRun([
                    metadata: 'metadata/pytests/vault.yaml',
                    test: 'vault',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "pytest::replica-install": {
                new TeRun([
                    metadata: 'metadata/pytests/replica-install.yaml',
                    test: 'ipa-replica-install',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "pytest::replica-promotion": {
                new TeRun([
                    metadata: 'metadata/pytests/ipa-replica-promotion.yaml',
                    test: 'ipa-replica-promotion',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "bash::krbtpolicy": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-krbtpolicy.yaml",
                    test: 'ipa-krbtpolicy',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "bash::sudo": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-sudo.yaml",
                    test: 'ipa-sudo',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "bash::password": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-password.yaml",
                    test: 'ipa-password',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "bash::cert": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-cert.yaml",
                    test: 'ipa-cert',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "bash::ipa-hbac-func": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-hbac-func.yaml",
                    test: 'ipa-hbac-func',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "bash::ssh-functional": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-ssh-functional.yaml",
                    test: 'ipa-ssh-functional',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "bash::user-cli-adduser": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-user-cli-adduser.yaml",
                    test: 'ipa-user-cli-adduser',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "bash::user-cli-moduser": {
                new TeRun([
                    metadata: "${IPATESTS_METADATA_PATH}/metadata/ipa-user-cli-moduser.yaml",
                    test: 'ipa-user-cli-moduser',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            },
            "pytest::func-svcs": {
                new TeRun([
                    metadata: 'metadata/pytests/functional-services.yaml',
                    test: 'ipa-functional-services',
                    message: "${params.CI_MESSAGE}"
                ]).exec('ipa-slave')
            }
            )
        }
   } catch (e) {
     echo 'failed'
     throw e
     echo "failed" > /tmp/tier1_status
   } finally {
     sh "rm -fr idm-ci"
     sh 'git clone -b gating https://gitlab.cee.redhat.com/ftrivino/idm-ci.git'
     echo 'Generating json message to be placed on UMB'
     sh "ansible-playbook -vvvv --connection=local -i localhost, idm-ci/playbooks/gating/gen_tier1_message.yaml"
     env.tier1json = readJSON file:'/tmp/tier1-results-umb.json'
     echo "${env.tier1json}"
     sh "cat /tmp/tier1-results-umb.json"
     echo "Placing the result on UMB"
     //retry(3) {
       //try {
           // 1 minute should be more than enough time to send the topic msg
           //timeout(1) {
             //try {
               // Send message and return SendResult
               //def msgContent = "${env.tier1json}"
               //println msgContent
               //sendResult = sendCIMessage \
                       //messageContent: msgContent, \
                       //messageProperties: '', \
                       //messageType: 'Custom', \
                       //overrides: [topic: 'VirtualTopic.eng.ci.redhat-module.test.complete'], \
                       //providerName: 'Red Hat UMB', \
                       //failOnError: true
               //return sendResult
               // echo sent message id and content
               //echo sendResult.getMessageId()
               //echo sendResult.getMessageContent()
             //} catch(e) {
                 //throw e
             //}
           //}
       //} catch(e) {
           //echo "FAIL: Could not send message to msg to UMB"
           //echo e.getMessage()
           //sleep 30
           //error e.getMessage()
       //}
     //}
  }


}
