"""
Overview:
IPA replica install bzs automation
#1283890
#1242036
SetUp Requirements:
-Master and Replica on latest version of RHEL OS
-The test use dummy data which is not used in actual installation.
"""

import pytest
from ipa_pytests.qe_class import multihost
from ipa_pytests.qe_class import qe_use_class_setup
from ipa_pytests.shared import paths
from ipa_pytests.qe_install import setup_master, setup_replica
from ipa_pytests.shared.rpm_utils import check_rpm


class TestBugCheck(object):
    """ Test Class """
    def class_setup(self, multihost):
        """ Setup for class """
        print("\nClass Setup")
        print("REPLICA: ", multihost.replica.hostname)
        print("\nChecking IPA server package whether installed on REPLICA")
        rpm_list = ['ipa-server']
        check_rpm(multihost.replica, rpm_list)

    def test_0001_bz1283890(self, multihost):
        """
        Testcase to validate IPA replica install parameters
        """
        exp_output = "ipa-replica-install: error: option --forwarder:"
        multihost.replica.qerun(['ipa-replica-install', '--forwarder=a.c.b.d'],
                                exp_returncode=2,
                                exp_output=exp_output)

    def test_0002_bz1283890(self, multihost):
        """
        Testcase to validate IPA replica install parameters
        """
        exp_output = "ipa-replica-install: error: you must provide a " \
                     "file generated by ipa-replica-prepare"
        multihost.replica.qerun(['ipa-replica-install'],
                                exp_returncode=2,
                                exp_output=exp_output)

    def test_0003_bz_1242036(self, multihost):
        """Master is configured using '--setup-dns'
        *.gpg file is installed on replica without using '--setup-dns'
        both master and replica give same output for 'dnsrecord-find testrelm.test' """
        setup_master(multihost.master)
        setup_replica(multihost.replica, multihost.master, False, False)
        multihost.master.kinit_as_admin()
        multihost.replica.kinit_as_admin()
        master_op = multihost.master.run_command(['ipa', 'dnsrecord-find', multihost.master.domain.name])
        multihost.replica.qerun(['ipa', 'dnsrecord-find', multihost.replica.domain.name],
                                exp_returncode=0,
                                exp_output=master_op.stdout_text)

    def class_teardown(self, multihost):
        """ Full suite teardown """
        pass
